module.exports = {
    afkModel: require("../afkModel"),
    tempMuteModel: require("../tempMuteModel"),
    prefixModel: require("../prefixModel"),
    premiumModel: require("../premiumModel"),
    suggestionModel: require("../suggestionsModel"),
    tagModel: require("../tagModel"),
    thanklbModel: require("../thanklbModel"),
    thanksModel: require("../thanksModel"),
    warnModel: require("../warnModel"),
    welcomeModel: require("../welcomeModel"),
    leaveModel: require("../leaveModel"),
    joinroleModel: require("../joinrole"),
    logsModel: require("../Messagelogs"),
    rolelogsModel: require("../roleLogs"),
    channellogsModel: require("../channelLogs"),
    serverlogsModel: require("../serverLogs"),
    ghostPingModel: require("../ghostPingModel"),
    muteModel: require("../muteModel"),
};
